version: '3.8'
services:
  postgres:
    image: 'postgres:12.2'
    expose:
      - 5432
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: exchangeapidemo
      POSTGRES_PASSWORD: exchangeapidemo
      POSTGRES_DB: exchangeapidemo
      PGGSSENCMODE: disable